pipeline {
	agent {
    node {
      label 'ibmi7.3'
    }
  }
  environment {
     NODE_PATH = '/QOpenSys/pkgs/lib/nodejs18/bin'
  }
  stages {
    stage('build') {
      steps {
        sh '''
            export PATH=$NODE_PATH:$PATH
            npm ci --production
            ./node_modules/.bin/node-pre-gyp rebuild --production
            ./node_modules/.bin/node-pre-gyp package
        '''
      }
    }
    stage('update-gh-release') {
      environment {
        GH_TOKEN = credentials('node-odbc-gh-token')
      }
      steps {
        sh '''
           export PATH=$NODE_PATH:$PATH
           export GITHUB_TOKEN=$GH_TOKEN_PSW
           node .github/upload-release-asset.js build/stage/*.tar.gz
        '''
      }
    }
  }
}
