const odbc = require('../../../lib/odbc');

module.exports = {
  generateCreateOrReplaceQueries: function(tableName, fields) {
    const sqlQueries = [];
    sqlQueries.push(`DROP TABLE IF EXISTS ${tableName}`);
    sqlQueries.push(`CREATE TABLE ${tableName} ${fields}`);
    sqlQueries.push(`CREATE OR REPLACE PROCEDURE TESTPROC(a1 OUT INTEGER) AS BEGIN  SELECT 1 INTO a1 FROM dual; END;`); // DB_STOREDPROCEDURE
    sqlQueries.push(`CREATE OR REPLACE PROCEDURE TESTPROC2(a1 OUT INTEGER, a2 OUT INTEGER) AS BEGIN  SELECT 1 INTO a1 FROM dual;  SELECT 2 INTO a2 FROM dual; END;`); // DB_STOREDPROCEDURE2
    return sqlQueries;
  },
  sqlColumnsColumns: [
   {
      "name":"TABLE_CAT",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_SCHEM",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"COLUMN_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"DATA_TYPE",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TYPE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":40,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"COLUMN_SIZE",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"BUFFER_LENGTH",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"DECIMAL_DIGITS",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"NUM_PREC_RADIX",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"NULLABLE",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"REMARKS",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":1,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"COLUMN_DEF",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":4000,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"SQL_DATA_TYPE",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"SQL_DATETIME_SUB",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"CHAR_OCTET_LENGTH",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"ORDINAL_POSITION",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"IS_NULLABLE",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":3,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"STORE_TYPE",
      "dataType":1,
      "dataTypeName":"SQL_CHAR",
      "columnSize":1,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"ENCRYPT",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"GEOMETRY",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   }
  ],
  sqlPrimaryKeysColumns : [
   {
      "name":"TABLE_CAT",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_SCHEM",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"COLUMN_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"KEY_SEQ",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"PK_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"INDEX_ID",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   }   
  ],
  sqlForeignKeysColumns: [
   {
      "name":"PKTABLE_CAT",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"PKTABLE_SCHEM",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"PKTABLE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"PKCOLUMN_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"FKTABLE_CAT",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"FKTABLE_SCHEM",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"FKTABLE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"FKCOLUMN_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":false
   },
   {
      "name":"KEY_SEQ",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"UPDATE_RULE",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"DELETE_RULE",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"FK_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"PK_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"DEFERRABILITY",
      "dataType":5,
      "dataTypeName":"SQL_SMALLINT",
      "columnSize":5,
      "decimalDigits":0,
      "nullable":true
   }   
  ],
  sqlTablesColumns: [
   {
      "name":"TABLE_CAT",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_SCHEM",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLE_TYPE",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":17,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"REMARKS",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":128,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"MAXROW",
      "dataType":-5,
      "dataTypeName":"SQL_BIGINT",
      "columnSize":19,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLESPACE_NAME",
      "dataType":12,
      "dataTypeName":"SQL_VARCHAR",
      "columnSize":40,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"TABLESPACE_TYPE",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"PCTFREE",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   },
   {
      "name":"PCTUSED",
      "dataType":4,
      "dataTypeName":"SQL_INTEGER",
      "columnSize":10,
      "decimalDigits":0,
      "nullable":true
   }   
  ]
};
